---
  - name: create install folder
    win_file: 
      path: '{{ citrix_installfolder }}'
      state: directory

  - name: Map SMB share
    win_shell: |
      net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

  - name: Copy Citrix iso to the local disk
    win_copy:
      src: '{{ citrix_ddc_srcisofile }}'
      remote_src: true
      dest: '{{ citrix_ddc_destisofile }}' 
      force: no

  - name: Unzip ISO
    community.general.iso_extract:
      image: '{{ citrix_ddc_destisofile }}'
      dest: '{{ citrix_installfolder }}\XD'

  - name: Copy script
    win_copy:
      src: '{{ item }}'
      dest: '{{ citrix_installfolder }}'
    with_fileglob:
      - '*.ps1'

  - name: Create Site
    script: 'files/installddc.ps1'
    args:
      creates: '{{ citrix_logfolder }}\install_ddc.txt'