---
  - name: create install folder
    win_file: 
      path: '{{ citrix_installfolder }}'
      state: directory

  - name: Map SMB share
    win_shell: |
      net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

  - name: Copy Citrix zip to the local disk
    win_copy:
      src: '{{ citrix_ddc_srczipfile }}'
      remote_src: true
      dest: '{{ citrix_ddc_destzipfile }}' 
      force: no

  - name: Unzip ISO
    community.windows.win_unzip:
      src: '{{ citrix_ddc_destzipfile }}'
      dest: '{{ citrix_installfolder }}'