---
- name: Prepare machine for auto-logon to support DDC installation - 1
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 1
    state: present

- name: Prepare machine for auto-logon to support DDC installation - 2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: '{{ ansible_user }}'
    state: present

- name: Prepare machine for auto-logon to support DDC installation - 3
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: '{{ ansible_password }}'
    state: present

- name: Install DDC Pre-Reqs
  win_feature:
    name: "{{ citrix_ddc_prereqs }}"
    state: present
  register: ddc_prereqs 

- name: Reboot if features require
  ansible.windows.win_reboot:
    post_reboot_delay: 120
  when: ddc_prereqs.reboot_required

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

- name: create install folder
  win_file: 
    path: '{{ citrix_installfolder }}'
    state: directory

- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ citrix_ddc_srcisofile }}"
    remote_src: true
    dest: "{{ citrix_ddc_destisofile }}" 
    force: no

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ citrix_ddc_destisofile }}"
    state: present
  register: disk_image_out

- name: Install DDC Components
  win_package:
    path: "{{ citrix_ddc_exepath }}"
    arguments: "{{ citrix_ddc_params_full }}"
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: 'C:\Program Files\Citrix\Desktop Studio'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ citrix_user_admin }}"
    ansible_become_pass: "{{ citrix_password_admin }}"

- name: Reboot
  ansible.windows.win_reboot:

- name: Remove DDC RunOnce Key
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: "!XenDesktopSetup"
    state: absent
  register: ddc_resume

- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: '{{ citrix_installfolder }}\{{ citrix_version_name }}.iso'
    state: present
  register: disk_image_out

- name: Resume DDC Install
  win_package:
    path: C:\ProgramData\Citrix\XenDesktopSetup\XenDesktopServerSetup.exe
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: 'C:\Program Files\Citrix\Desktop Studio'
  when: ddc_resume.changed

- name: Reboot
  ansible.windows.win_reboot:

- name: Remove auto-logon reg keys - 1
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    state: absent

- name: Remove auto-logon reg keys - 2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    state: absent

- name: Remove auto-logon reg keys - 3
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    state: absent

- name: Reboot
  ansible.windows.win_reboot: