---
  - name: create install folder
    win_file: 
      path: '{{ citrix_installfolder }}'
      state: directory

  - name: Map SMB share
    win_shell: |
      net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

  - name: Copy Citrix zip to the local disk
    win_copy:
      src: '{{ citrix_ddc_srczipfile }}'
      remote_src: true
      dest: '{{ citrix_ddc_destzipfile }}' 
      force: no

  - name: Unzip ZIP
    community.windows.win_unzip:
      src: '{{ citrix_ddc_destzipfile }}'
      dest: '{{ citrix_installfolder }}'

  - name: Install DDC Components
    win_package:
      path: "{{ citrix_ddc_exepath }}"
      arguments: "{{ citrix_ddc_params_full }}"
      state: present
      expected_return_code: [0, 3, 3010]
      creates_path: 'C:\Program Files\Citrix\Desktop Studio'
    become: yes
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: "{{ citrix_user_admin }}"
      ansible_become_pass: "{{ citrix_password_admin }}"
    register: ddc_install_started