---
- name: Install Required Server Roles for Citrix
  win_feature:
    name: "{{ req_roles }}"
    state: present
  register: requirements

- name: Reboot when Required Roles need a restart
  ansible.windows.win_reboot:
    post_reboot_delay: 120

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.18 "deviceTRUST$" /user:share

- name: create folder
  win_file: 
    path: "C:\\ansible_install"
    state: directory

- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ srcisofile }}"
    remote_src: true
    dest: "{{ destisofile }}" 
    force: no

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ destisofile }}"
    state: present
  register: disk_image_out

- name: Install DDC Components
  win_package:
    path: "{{ exepath }}"
    arguments: "{{ params_full }}"
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: 'C:\Program Files\Citrix\Desktop Studio'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ dc_admin_domain }}"
    ansible_become_pass: "{{ dc_password_admin }}"
  register: ddc_install

- name: Reboot
  ansible.windows.win_reboot:
  when: ddc_install.changed

- name: Remove DDC RunOnce Key
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: "!XenDesktopSetup"
    state: absent
  register: ddc_resume

- name: Ensure an ISO is mounted
  community.windows.win_disk_image:
    image_path: C:\Install\{{ citrix_version_name }}.iso
    state: present
  register: disk_image_out

- name: Resume DDC Install
  win_package:
    path: C:\ProgramData\Citrix\XenDesktopSetup\XenDesktopServerSetup.exe
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: 'C:\Program Files\Citrix\Desktop Studio'
  when: ddc_resume.changed

- name: Reboot
  ansible.windows.win_reboot: