---
- name: Install DDC Pre-Reqs
  win_feature:
    name: "{{ citrix_ddc_prereqs }}"
    state: present
  register: ddc_prereqs 

- name: Reboot if features require
  win_reboot:
  when: win_feature.reboot_required

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.22 '{{ smb_share_password }}' /user:'{{ smb_share_username }}'

- name: Create install folder
  win_file: 
    path: '{{ citrix_installfolder }}'
    state: directory

- name: Create log folder
  win_file: 
    path: '{{ citrix_logfolder }}'
    state: directory

- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ citrix_ddc_srcisofile }}"
    remote_src: true
    dest: "{{ citrix_ddc_destisofile }}" 
    force: no

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ citrix_ddc_destisofile }}"
    state: present
  register: disk_image_out

- name: Install DDC Components
  win_package:
    path: "{{ citrix_ddc_exepath }}"
    arguments: "{{ citrix_ddc_params_full }}"
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: 'C:\Program Files\Citrix\Desktop Studio'
  register: ddc_install

- name: Reboot after DDC
  win_reboot:
  when: ddc_install.changed

- name: Remove DDC RunOnce Key
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: "!XenDesktopSetup"
    state: absent
  register: ddc_resume

- name: Resume DDC Install
  win_package:
    path: C:\ProgramData\Citrix\XenDesktopSetup\XenDesktopServerSetup.exe
    state: present
    expected_return_code: [0, 3, 3010]
    creates_path: C:\Program Files\Citrix\Desktop Studio
  when: ddc_resume.changed